[package]
name = "myapp"
version = "0.1.0"
authors = [""]
edition = "2021"

[dependencies]
actix-web = "4"
bson = "2.0.0"
chrono = "0.4.19"
futures = "0.3.17"
mongodb = "2.0.0"
serde = { version = "1.0", features = ["derive"] }